src/CS.Api/Controllers/ProfessorController.cs
using System.Net;
using CS.Application.Interface;
using CS.Application.Model;
using CS.Application.Response;
using CS.Core.Notificador;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

namespace CS.Api.Controllers
{
    [Route("[controller]")]
    public class ProfessorController : BaseController
    {
        private readonly IProfessorService _professorService;

        public ProfessorController(IProfessorService professorService,
            INotificador notificador) : base(notificador)
        {
            _professorService = professorService;
        }

        [HttpPost, Authorize(Roles = "admin")]
        [SwaggerResponse((int)HttpStatusCode.OK, "", typeof(Response<Guid?>))]
        public async Task<IActionResult> Adicionar([FromBody] CriarProfessorModel model)
        {
            var response = await _professorService.Adicionar(model);
            return CustomResponse(response);
        }

        [HttpDelete, Authorize(Roles = "admin")]
        [SwaggerResponse((int)HttpStatusCode.OK, "", typeof(Response<bool>))]
        public async Task<IActionResult> Remover([FromBody] RemoverEntidadeModel model)
        {
            await _professorService.Remover(model);
            return CustomResponse(true);
        }

        [HttpPut, Authorize(Roles = "admin")]
        [SwaggerResponse((int)HttpStatusCode.OK, "", typeof(Response<bool>))]
        public async Task<IActionResult> Atualizar([FromBody] AtualizarProfessorModel model)
        {
            await _professorService.Atualizar(model);
            return CustomResponse(true);
        }

        [HttpPut("senha"), Authorize(Roles = "admin")]
        [SwaggerResponse((int)HttpStatusCode.OK, "", typeof(Response<bool>))]
        public async Task<IActionResult> AtualizarSenha([FromBody] AtualizarSenhaModel model)
        {
            await _professorService.AtualizarSenha(model);
            return CustomResponse(true);
        }

        [HttpGet("id"), Authorize(Roles = "admin")]
        [SwaggerResponse((int)HttpStatusCode.OK, "", typeof(Response<ProfessorResponse>))]
        public async Task<IActionResult> ObterPorId(Guid id)
        {
            var response = await _professorService.ObterPorId(id);
            return CustomResponse(response);
        }

        [HttpGet, Authorize(Roles = "admin")]
        [SwaggerResponse((int)HttpStatusCode.OK, "", typeof(Response<List<ProfessorResponse>>))]
        public async Task<IActionResult> Obter()
        {
            var response = await _professorService.Obter();
            return CustomResponse(response);
        }
    }
}

src/CS.Api/Pages/Novo/ProfessorNovo.cshtml.cs
namespace CS.Api.Pages.Novo
{
    public class ProfessorNovoModel : BaseAuthorizePageModelModel
    {
        public void OnGet()
        {
        }
    }
}

src/CS.Api/Pages/Novo/ProfessorNovo.cshtml
@page
@model CS.Api.Pages.Novo.ProfessorNovoModel
@{
    Layout = "_CadastroEntidade";
    ViewData["tituloFuncao"] = "Cadastro de professor";
}

<div class="row">
    <div class="col-xl-4">
        <label for="Nome" class="d-flex form-label">Nome</label>
        <div class="form-group" data="">
            <div class="input-group" data-target-input="nearest">
                <input type="text" id="Nome" name="Nome" class="form-control" value="" autocomplete="off">
            </div>
        </div>
    </div>
    <div class="col-xl-4">
        <label for="CPF" class="d-flex form-label">CPF</label>
        <div class="form-group" data="">
            <div class="input-group" data-target-input="nearest">
                <input type="text" maxlength="11" id="CPF" name="CPF" class="form-control" value="" autocomplete="off">
            </div>
        </div>
    </div>
    <div class="col-xl-4">
        <label for="DataNascimento" class="d-flex form-label">Data de nascimento</label>
        <div class="form-group" data="">
            <div class="input-group input-date" id="DataInicial_container" data-target-input="nearest">
                <input type="text" maxlength="10" id="DataNascimento" name="DataNascimento" class="form-control date datepicker-input" data-target="#DataInicial_container" value="" data-mask="date" autocomplete="off">
                <div class="input-group-append" data-target="#DataInicial_container">
                    <button type="button" class="btn btn-outline-primary py-2 my-0 px-4 " data-bs-toggle="tooltip" tabindex="-1">
                        <i class=" fa fa-calendar"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-4">
        <label for="Email" class="d-flex form-label">Email</label>
        <div class="form-group" data="">
            <div class="input-group" data-target-input="nearest">
                <input type="text" id="Email" name="Email" class="form-control" value="" autocomplete="off">
            </div>
        </div>
    </div>
    <div class="col-xl-4">
        <label for="Senha" class="d-flex form-label">Senha</label>
        <div class="form-group">
            <div class="input-group">
                <input type="password" id="Senha" name="Senha" class="form-control">
                <div class="input-group-append">
                    <button type="button" class="btn btn-outline-primary py-2 my-0 px-4 " title="Visualizar a senha" data-bs-toggle="tooltip" onclick="visualizeSenha(this, event)" tabindex="-1">
                        <i style="color: black;" class="fa fa-eye-slash"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<script defer>
EventDomContentLoaded(() => {
    const botaoCancelar = document.getElementById('cancelar');
    botaoCancelar.addEventListener('click', (ev) => {
        ev.preventDefault();
        new Modal().confirmacao("Tem certeza que deseja cancelar o cadastro ?", () => {
            window.location.href = '/Cadastro/Professor';
        }).render();
    })
    const botaoCadastrar = document.getElementById('gravar');
    botaoCadastrar.addEventListener('click', gravarCadastro);
});

async function gravarCadastro(ev) {
    ev.preventDefault();

    const url = '@Url.Action("Adicionar", "Professor")';
    const data = {
        Nome: Nome.value,
        Cpf: CPF.value,
        DataNascimento: DataNascimento.value.convertaStrLocaleToDate(),
        Email: Email.value,
        Senha: Senha.value
    }
    const resposta = await postJSON(url, data);
    if (resposta && resposta.success) {
        new Modal().sucesso("Professor cadastrado com sucesso").depoisDeOcultar(() => {
            window.location.href = '/Cadastro/Professor';
        }).render();
    }
}
</script>