src/CS.Api/Componentes/ViewComponent/Grid/GridViewComponent.cs
namespace CS.Api.Componentes.ViewComponent.Grid;

using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

public class GridViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(dynamic options)
    {
        GridOptions gridOptions = options["options"].Field;

        ViewData["id"] = !string.IsNullOrEmpty(gridOptions.Id) ? gridOptions.Id : gridOptions.GetElementId;
        ViewData["name"] = gridOptions.AspFor;
        ViewData["columnsParams"] = JsonSerializer.Serialize(gridOptions.Colunas);
        ViewData["acoes"] = JsonSerializer.Serialize(gridOptions.Acoes);
        ViewData["ordenacaoPadraoCrescente"] = gridOptions.OrdenacaoPadraoCrescente;
        ViewData["ordenacaoPadrao"] = JsonSerializer.Serialize(gridOptions.OrdenacaoPadrao);
        ViewData["permiteUnicaSelecao"] = gridOptions.PermiteUnicaSelecao;
        ViewData["permiteMultiplaSelecao"] = gridOptions.PermiteMultiplaSelecao;
        ViewData["permiteMultiplaExclusao"] = gridOptions.PermiteMultiplaExclusao;
        ViewData["permitePesquisa"] = gridOptions.PesquisePor.Any();
        ViewData["pesquisePor"] = gridOptions.PesquisePor.ToArray();

        return View();
    }
}

src/CS.Api/Controllers/ProfessorController.cs
using System.Net;
using CS.Application.Interface;
using CS.Application.Model;
using CS.Application.Response;
using CS.Core.Notificador;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

namespace CS.Api.Controllers
{
    [Route("[controller]")]
    public class ProfessorController : BaseController
    {
        private readonly IProfessorService _professorService;

        public ProfessorController(IProfessorService professorService,
            INotificador notificador) : base(notificador)
        {
            _professorService = professorService;
        }

        [HttpPost, Authorize(Roles = "admin")]
        [SwaggerResponse((int)HttpStatusCode.OK, "", typeof(Response<Guid?>))]
        public async Task<IActionResult> Adicionar([FromBody] CriarProfessorModel model)
        {
            var response = await _professorService.Adicionar(model);
            return CustomResponse(response);
        }

        [HttpDelete, Authorize(Roles = "admin")]
        [SwaggerResponse((int)HttpStatusCode.OK, "", typeof(Response<bool>))]
        public async Task<IActionResult> Remover([FromBody] RemoverEntidadeModel model)
        {
            await _professorService.Remover(model);
            return CustomResponse(true);
        }

        [HttpPut, Authorize(Roles = "admin")]
        [SwaggerResponse((int)HttpStatusCode.OK, "", typeof(Response<bool>))]
        public async Task<IActionResult> Atualizar([FromBody] AtualizarProfessorModel model)
        {
            await _professorService.Atualizar(model);
            return CustomResponse(true);
        }

        [HttpPut("senha"), Authorize(Roles = "admin")]
        [SwaggerResponse((int)HttpStatusCode.OK, "", typeof(Response<bool>))]
        public async Task<IActionResult> AtualizarSenha([FromBody] AtualizarSenhaModel model)
        {
            await _professorService.AtualizarSenha(model);
            return CustomResponse(true);
        }

        [HttpGet("id"), Authorize(Roles = "admin")]
        [SwaggerResponse((int)HttpStatusCode.OK, "", typeof(Response<ProfessorResponse>))]
        public async Task<IActionResult> ObterPorId(Guid id)
        {
            var response = await _professorService.ObterPorId(id);
            return CustomResponse(response);
        }

        [HttpGet, Authorize(Roles = "admin")]
        [SwaggerResponse((int)HttpStatusCode.OK, "", typeof(Response<List<ProfessorResponse>>))]
        public async Task<IActionResult> Obter()
        {
            var response = await _professorService.Obter();
            return CustomResponse(response);
        }
    }
}

src/CS.Api/Pages/Cadastro/Professor.cshtml.cs
using CS.Application.Interface;
using CS.Application.Response;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace CS.Api.Pages.Cadastro
{
    public class ProfessorModel : BaseAuthorizePageModelModel
    {
        public List<ProfessorResponse> Professores { get; }
        private readonly IProfessorService _professorService;

        public ProfessorModel(IProfessorService professorService)
        {
            _professorService = professorService;
        }

        public async Task<IActionResult> OnGet()
        {
            var professores = await _professorService.Obter();
            ViewData["professores"] = JsonSerializer.Serialize(professores);
            
            return Page();
        }
    }
}

src/CS.Api/Pages/Cadastro/Professor.cshtml
@page
@model CS.Api.Pages.Cadastro.ProfessorModel
@{
    Layout = "_LayoutPage";
    ViewData["tituloFuncao"] = "Professores";
}

<script type="text/template" id="TemplateDataNascimento"> 
    ${formateData(row.DataNascimento)}
</script>

<div class="row">
    <div class="col-xl-12">
        <vc:grid options="@(Html.GridOptions(m => m.Professores)
                                .AddColumn(c => c.Bound(m => m.Nome))
                                .AddColumn(c => c.Bound(m => m.Cpf).Title("CPF"))
                                .AddColumn(c => c.Bound(m => m.Email))
                                .AddColumn(c => c.Template("#TemplateDataNascimento").Title("Data de nascimento"))
                                .AddAction(a => a.Remover())
                                .AddAction(a => a.Editar()))"></vc:grid>
    </div>
</div>

<script defer>
let professores;
    EventDomContentLoaded(() => {
        let professores = JSON.parse('@Html.Raw(ViewData["professores"])');
        Grid_Professores.addRange(professores);

        const botaoCadastrar = document.querySelector('.botao-cadastrar');
        botaoCadastrar.addEventListener('click', (ev) => {
            ev.preventDefault();
            window.location.href = '/Novo/ProfessorNovo';
        });
    });
</script>